### PR TITLE
Fix a bug preventing spouse and sibling events from showing up

### PR DESCRIPTION
**Pull request by Joppla**

### CODE REVIEW

**Comment by dkniffin** [comment]
Nice! Thanks for doing this. I got busier today than I thought I would be.

**Comment by dkniffin** [comment]
Fixes #23

**Comment by Joppla** [comment]
When will it be in a downloadable zip?

**Comment by dkniffin** [comment]
I'll go ahead and make the other change, then push up a release and update the readme with the new zip.

**Comment by dkniffin** [comment]
Alright, 1.8 is released, and the readme is updated. You can get the new zip [here](https://github.com/dkniffin/webtrees-openstreetmap/archive/v1.8.zip)

**Pull request merged**
