### PR TITLE
Joppla patch 2

### PR DESCRIPTION
**Pull request by Joppla**
Is this the right way?

### CODE REVIEW

**Review by Joppla — COMMENTED** [review]
Please review line 210. $_GET seems me not a very save method to get the name of the database

**Comment by dkniffin** [comment]
Thanks for the PR, @Joppla! I'll review it when I get some time, but I don't know when that will be. Unfortunately, I'm not using this plugin (or webtrees for that matter) much right now, so it's not a big priority for me.

**Comment by Joppla** [comment]
Ok, thanks for your reaction. Does this mean that the module won't be developed much further?

**Comment by Joppla** [comment]
Forget the whole PR, I will make an better one.

**Comment by dkniffin** [comment]
I will probably develop it further, especially when I start doing some more genealogy research, but I'm not doing much right now.

**Comment by Joppla** [comment]
I don't mind to do some work for the Module. But if there is nothing done with it, then it is maybe better to start my own project with it.

**Pull request closed without merging**
