### PR TITLE
make tile source configurable: you can choose now osm or mapbox

### PR DESCRIPTION
**Pull request by aquast**

### CODE REVIEW

**Comment by dkniffin** [comment]
Would you mind providing a screenshot of what this looks like? I think I know, but I want to make sure this is what I think it is.

**Comment by aquast** [comment]
screen

**Comment by aquast** [comment]
The pull requests purpose is to allow users to choose from different TileLayers. Pherhaps it's possible later on to make persons from the markers Layer selectable too.

**Comment by dkniffin** [comment]
👍 Looks good to me. There are [some limits](http://wiki.openstreetmap.org/wiki/Tile_usage_policy) on using the OSM tiles, but I _think_ this is okay.

**Pull request merged**
